myriad/coverage (#65)
* myriad/coverage

* Include dev deps too

* Coverage dev tools

* Include coverage on merge to master

* Test coverage step

* Fix up YAML layout

* Include coverage badge

* Include path for local installs, and run under dzil environment

* Ignore coverage test failures - some of our modules trigger extra warnings in that mode

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,7 +24,7 @@ jobs:
       - run:
           name: Install deps
           command: |
-            cpanm -l deps --installdeps -n .
+            cpanm -l deps --installdeps --with-develop -n .
       - save_cache:
           key: cpanfile-{{ arch }}-{{ checksum "cpanfile" }}
           paths:
@@ -39,6 +39,32 @@ jobs:
           command: |
             export PERL5LIB=$(pwd)/deps/lib/perl5:$(pwd)/deps/lib/perl5/$(perl -MConfig -le'print $Config{archname}'):$PERL5LIB
             dzil xtest
+
+  coverage:
+    docker:
+      - image: deriv/dzil:latest
+        entrypoint: /bin/bash
+    steps:
+      - checkout
+      - run:
+          name: Prepare environment
+          command: |
+            apt-get update
+            apt-get -y -q --no-install-recommends install $(cat aptfile)
+      - restore_cache:
+          keys:
+            - cpanfile-{{ arch }}-{{ checksum "cpanfile" }}
+      - run:
+          name: Install deps
+          command: |
+              cpanm -l deps --installdeps --with-develop -n .
+      - run:
+          name: Coverage
+          command: |
+              export PERL5LIB=$(pwd)/deps/lib/perl5:$(pwd)/deps/lib/perl5/$(perl -MConfig -le'print $Config{archname}'):$PERL5LIB
+              export PATH=$(pwd)/deps/bin:$PATH
+              # We don't care about failures here: those are handled by the main tests, we just want the report
+              dzil run cover -test -report coveralls || :
   
   update_docker_image:
     executor: docker/docker
@@ -65,6 +91,8 @@ workflows:
     jobs:
       - run_tests:
           context: perl
+          filters: *filter_only_master
+      - coverage:
           filters: *filter_only_master
       - update_docker_image:
           context: perl
